---

- debug: var=ansible_distribution

- name: checking if td-agent is installed
  shell: type td-agent >/dev/null 2>&1 || { echo "~none~"; exit 0; }
  register: tdAgentPath
  ignore_errors: True

- debug: var=tdAgentPath.stdout

- name: Check td_agent_architecture is defined if os is Debian
  fail: msg="define 'td_agent_architecture', i386 or amd64.\nDetail for http://docs.fluentd.org/articles/install-by-deb"
  when: ansible_distribution == "Debian" and ansible_distribution_version[0] == '6' and td_agent_architecture not in ['i386', 'amd64']

- include: redhat_td-agent.yml
  when: ansible_os_family == "RedHat"

- include: ubuntu_td-agent.yml
  when: ansible_distribution == "Ubuntu"

- include: debian_td-agent.yml
  when: ansible_distribution == "Debian" and ansible_distribution_version[0] == '6'

- name: Setting up the td-agent.conf
  template: src=td-agent.conf.j2 dest=/etc/td-agent/td-agent.conf