---

- name: install dependencies...
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - python-pycurl

- name: installing the td-agent
  shell: curl -L http://toolbelt.treasuredata.com/sh/install-ubuntu-precise.sh | sh
  when: tdAgentPath.stdout == "~none~"
  notify:
    - restart td-agent
